; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#ifndef MyAppVersion
  #define MyAppVersion "1.0.0.0"
#endif
#define MyAppPublisher "K700, cmpxchg8b, AgentSmith"
#define MyAppURL "https://forums.taleworlds.com/index.php?threads/warband-script-enhancer-2-v1-1-1-5.384882/"
#define MyAppExeName "wse2_launcher.exe"

#ifndef WFaS
  #define MyAppName "Warband Script Enhancer 2"
  #define WSE_Path ".\files\WSE2"
  #define MyDefaultDirName "{reg:HKLM\SOFTWARE\Mount&Blade Warband,Install_Path|{commonpf}\Mount&Blade Warband}\"
  #define MyOutputBaseFilename "WSE2_Installer"
#else
  #define MyAppName "Warband Script Enhancer 2 WFaS"
  #define WSE_Path ".\files\WSE2 WFaS"
  #define MyDefaultDirName "{reg:HKLM\SOFTWARE\Mount&Blade With Fire and Sword,Install_Path|{commonpf}\Mount&Blade With Fire and Sword}\"
  #define MyOutputBaseFilename "WSE2_WFaS_Installer"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C92628E7-333E-4CDA-B4B9-AB3EB028E15E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} (v{#MyAppVersion})
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AppendDefaultDirName=no
DefaultDirName={#MyDefaultDirName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
DirExistsWarning=no
OutputBaseFilename={#MyOutputBaseFilename}
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
SetupIconFile=Images\iconwb.ico
Compression=lzma
SolidCompression=yes
Uninstallable=no
WizardStyle=classic
WizardSmallImageFile=Images\mb_inst_top.bmp
WizardImageFile=Images\mb_inst_left.bmp

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}";
Name: "steam_shortcut"; Description: "Add to your steam library";  Check: has_shortcuts_dir
Name: "copy_profiles"; Description: "Copy profiles"; Check: can_copy_profiles

[Files]
Source: "{#WSE_Path}\*"; Excludes: "*dedicated*,*server*,\WSE2 SDK\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs
;Below is an empty placeholder file in case the steam user doesnt have a shortcuts.vdf yet
Source: ".\files\shortcuts.vdf"; DestDir: "{code:find_shortcuts_dir}"; Check: WizardIsTaskSelected('steam_shortcut'); Flags: onlyifdoesntexist
Source: ".\files\vdf-shortcut-editor.exe"; DestDir: "{app}"; Flags: deleteafterinstall
#ifndef WFaS
  Source: "{userappdata}\Mount&Blade Warband\profiles.dat"; DestDir: "{userappdata}\Mount&Blade Warband WSE2\"; Check: can_copy_profiles() and WizardIsTaskSelected('copy_profiles'); Flags: onlyifdoesntexist external
#else
  Source: "{userappdata}\Mount&Blade With Fire and Sword\profiles.dat"; DestDir: "{userappdata}\Mount&Blade WFaS WSE2\"; Check: can_copy_profiles() and WizardIsTaskSelected('copy_profiles'); Flags: onlyifdoesntexist external
#endif

[Icons]
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
#ifndef WFaS
  Filename: "{app}\vdf-shortcut-editor.exe"; Parameters: """{code:get_shortcuts_file}"" -a -1287593386 ""Mount & Blade: Warband WSE2"" ""{app}\{#MyAppExeName}"""; StatusMsg: "Adding to steam..."; Flags: runhidden; Check: WizardIsTaskSelected('steam_shortcut');
#else
  Filename: "{app}\vdf-shortcut-editor.exe"; Parameters: """{code:get_shortcuts_file}"" -a -1287593386 ""Mount & Blade With Fire and Sword WSE2"" ""{app}\{#MyAppExeName}"""; StatusMsg: "Adding to steam..."; Flags: runhidden; Check: WizardIsTaskSelected('steam_shortcut');
#endif
Filename: {app}\wse2_launcher.exe; Description: Start WSE2; Flags: postinstall nowait skipifsilent

[Code]
type BUTTON_IMAGELIST = record
  himl: THandle;
  margin: TRect;
  uAlign: UINT;
end;

const
  ILC_COLOR32 = $20;
  BCM_SETIMAGELIST = $1600 + $0002;
  IDI_WARNING = 32515;
  IDI_SHIELD = 32518;

///////////////////////////////////////////////////////////////////////////
//                              Imports
///////////////////////////////////////////////////////////////////////////
procedure ExitProcess(uExitCode: UINT);
  external 'ExitProcess@kernel32.dll stdcall';

function ShellExecute(hwnd: HWND; lpOperation: string; lpFile: string;
  lpParameters: string; lpDirectory: string; nShowCmd: Integer): THandle;
  external 'ShellExecuteW@shell32.dll stdcall';

function LoadIcon(
  hInst: Integer; IconName: Integer): THandle;
  external 'LoadIconW@User32.dll stdcall';

function ImageList_AddIcon(
  ImageList: THandle; Icon: THandle): Integer;
  external 'ImageList_AddIcon@Comctl32.dll stdcall';

function ImageList_Create(CX, CY: Integer; Flags: UINT;
  Initial, Grow: Integer): THandle;
  external 'ImageList_Create@Comctl32.dll stdcall';

function SendSetImageListMessage(
  Wnd: THandle; Msg: Cardinal; WParam: Cardinal;
  var LParam: BUTTON_IMAGELIST): Cardinal;
  external 'SendMessageW@User32.dll stdcall';

///////////////////////////////////////////////////////////////////////////
//                          Global Variables
///////////////////////////////////////////////////////////////////////////
var
  DirOk_Label, Finished_Notice_Label: TNewStaticText;
  UAC_ImageList: THandle;
  UAC_ButtonImageList: BUTTON_IMAGELIST;
  dir_skipped: Boolean;

///////////////////////////////////////////////////////////////////////////
//                               Code
///////////////////////////////////////////////////////////////////////////
function find_shortcuts_dir(Param: string): string;
var
  success: boolean;
  active_usr : Cardinal;
  shortcut_path, usr_dir, found_dir: string;
  info : TFindRec;
begin
  result := '';
  
  success := RegQueryStringValue(HKEY_CURRENT_USER, 'Software\Valve\Steam', 'SteamPath', usr_dir);
  if not success then begin Exit; end;
  usr_dir := usr_dir + '/userdata/';
  if not DirExists(usr_dir) then begin Exit; end;
  
  //First see if a user is logged into steam and use that id
  success := RegQueryDWordValue(HKEY_CURRENT_USER, 'Software\Valve\Steam\ActiveProcess', 'ActiveUser', active_usr);
  if success and (active_usr <> 0) then begin
    shortcut_path := usr_dir + IntToStr(active_usr) + '/config';
    
    if DirExists(shortcut_path) then begin
      result := shortcut_path;
      Exit;  
    end; 
  end;
  
  //Next we look if there is a single user folder (not counting "0")
  If FindFirst(usr_dir + '*', info) then
  begin
    found_dir := '';
    try
      Repeat
        if info.Attributes and FILE_ATTRIBUTE_DIRECTORY <> 0 then begin
          if (info.Name <> '0') and (info.Name <> '.') and (info.Name <> '..') then begin
            if found_dir <> '' then begin //if we already found a folder, it means there are multiple accounts. Abort
              result := '';
              Exit;
            end;
            found_dir := info.Name;
          end;
        end;
      Until not FindNext(info);
    finally
      FindClose(info);
    end;
  end;
  
  if found_dir <> '' then begin
    shortcut_path := usr_dir + found_dir + '/config';
    if DirExists(shortcut_path) then begin
      result := shortcut_path;
      Exit;  
    end;  
  end;   
end;

function get_shortcuts_file(Param: string): string;
var
  shortcuts_dir: string;
begin
  shortcuts_dir := find_shortcuts_dir('');
  if shortcuts_dir = '' then begin Exit; end;

  result := shortcuts_dir + '/shortcuts.vdf';
end;

function has_shortcuts_dir(): boolean;
begin
  result := (find_shortcuts_dir('') <> '');
end;

function can_copy_profiles(): boolean;
begin
#ifndef WFaS
  result := FileExists(ExpandConstant('{userappdata}\Mount&Blade Warband\profiles.dat')) and not FileExists(ExpandConstant('{userappdata}\Mount&Blade Warband WSE2\profiles.dat'))
#else
  result := FileExists(ExpandConstant('{userappdata}\Mount&Blade With Fire and Sword\profiles.dat')) and not FileExists(ExpandConstant('{userappdata}\Mount&Blade WFaS WSE2\profiles.dat'))
#endif
end;

//Path can have folders that don't exist yet, return the existing part
function ExtractExistingPath(Path: string): string;
begin
  Result := Path;
  while not DirExists(Path) do begin
    Path := ExtractFileDir(Path);
    if Path = Result then begin //quit infinite loop
      Result := '';
      Exit;
    end;
    Result := Path;
  end;
end;

function HaveWriteAccessToAppFolder: Boolean;
var
  FileName: string;
begin
  FileName := AddBackslash(ExtractExistingPath(WizardDirValue)) + '_writetest.tmp';
  Result := SaveStringToFile(FileName, 'test', False);
  if Result then begin DeleteFile(FileName); end;
end;

procedure Set_UAC_icon(show: Boolean);
begin
  if show then begin
    UAC_ButtonImageList.himl := UAC_ImageList;
    SendSetImageListMessage(WizardForm.NextButton.Handle, BCM_SETIMAGELIST, 0, UAC_ButtonImageList);
  end
  else begin
    UAC_ButtonImageList.himl := 0;
    SendSetImageListMessage(WizardForm.NextButton.Handle, BCM_SETIMAGELIST, 0, UAC_ButtonImageList);
  end;
end;

function HasParam(Param: String): Boolean;
var
  i: Integer;
  s : String;
begin
  Result := False;
  Param := '/'+Param;
  for i := 1 to ParamCount do begin
    s := ParamStr(i);

    if (CompareText(s, Param) = 0) or
       (Pos(Param+'=', s) = 1)
    then begin
      Result := True;
      Exit;
    end;
  end;
end;
///////////////////////////////////////////////////////////////////////////
//                              Events
///////////////////////////////////////////////////////////////////////////

procedure OnDirChanged(Sender: TObject);
begin
#ifndef WFaS
  if FileExists(WizardForm.DirEdit.Text + '\mb_warband.exe') then begin
    DirOk_Label.Caption := '✓ Game found';
    DirOk_Label.Font.Color := clGreen;
  end
  else begin
    DirOk_Label.Caption := 'x Couldn''t find mb_warband.exe - Select your M&&B Warband folder.';
    DirOk_Label.Font.Color := clMaroon;
  end;
#else
  if FileExists(WizardForm.DirEdit.Text + '\mb_wfas.exe') then begin
    DirOk_Label.Caption := '✓ Game found';
    DirOk_Label.Font.Color := clGreen;
  end
  else begin
    DirOk_Label.Caption := 'x Couldn''t find mb_wfas.exe - Select your M&&B WFaS folder.';
    DirOk_Label.Font.Color := clMaroon;
  end;
#endif

  //If we have /UAC it means this instance was started elevated already, 
  //if we still don't have write access then something else is wrong
  if not HasParam('UAC') then begin 
    Set_UAC_icon(not HaveWriteAccessToAppFolder()); 
  end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  path, params: String;
  RetVal: Integer;
begin
  Result := True;
  if CurPageID <> wpSelectDir then begin Exit; end;

  if (not HaveWriteAccessToAppFolder()) and not HasParam('UAC') then begin
    //Restart with elevated priviliges
    path := ExpandConstant('{srcexe}');
    params := Format('/Dir="%s" /UAC /Left="%d" /Top="%d"', [WizardDirValue, WizardForm.Left, WizardForm.Top]);

    RetVal := ShellExecute(0, 'runas', path, params, '', SW_SHOW);
    if (RetVal>32) then
    begin
      ExitProcess(0);
    end
    else begin
      MsgBox('Unable to launch the elevated process. Code ' + IntToStr(RetVal), mbError, MB_OK);
      Set_UAC_icon(false);
    end;
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
var
  p: string;
  num: Integer;
begin
  if CurPageID = 1 then begin
    //Restore window pos (UAC launch)
    num := StrToIntDef(ExpandConstant('{param:Left}'), -99999);
    if num <> -99999 then begin WizardForm.Left := num; end;
    num := StrToIntDef(ExpandConstant('{param:Top}'), -99999);
    if num <> -99999 then begin WizardForm.Top := num; end;
  end
  else if CurPageID = wpSelectDir then begin                                                                          
    OnDirChanged(nil);

    if HasParam('UAC') and HasParam('Dir') and not dir_skipped then begin
      //Setup got started by itself with elevated rights
      //Skip dir page once
      dir_skipped := True;
      WizardForm.NextButton.OnClick(nil);
    end;
  end
  else if (CurPageID = wpReady) and WizardIsTaskSelected('steam_shortcut') then begin
    p := get_shortcuts_file('');
    with Wizardform.ReadyMemo.Lines do begin
      Add('');
      Add('**Notice**');
      Add('    In order to add WSE2 to your steam library, setup will modify');
      Add('    "' + p + '"');
      Add('    A backup is created in the same folder with .bak ending');
      Add('    If something goes wrong, you can restore from this file.');
    end;
  end
  else if (CurPageID = wpFinished) then begin
    if WizardIsTaskSelected('steam_shortcut') then begin
      Finished_Notice_Label.Show();
    end 
  end
end;

procedure InitializeWizard();
var 
  ShieldIcon: THandle;
begin
  WizardForm.DirEdit.OnChange := @OnDirChanged;

  //Indicate if warband exe found
  DirOk_Label := TNewStaticText.Create(WizardForm.SelectDirPage);
  DirOk_Label.Parent := WizardForm.SelectDirPage;
  DirOk_Label.Top := WizardForm.DirEdit.Top + WizardForm.DirEdit.Height + ScaleY(8);
  DirOk_Label.Left := WizardForm.DirEdit.Left;
  DirOk_Label.Caption := 'My checkbox';
  // See https://stackoverflow.com/q/30469660/850848
  DirOk_Label.Height := ScaleY(DirOk_Label.Height);

  //Load UAC icon
  ShieldIcon := LoadIcon(0, IDI_SHIELD);
  UAC_ImageList := ImageList_Create(ScaleX(16), ScaleY(16), ILC_COLOR32, 1, 1);
  ImageList_AddIcon(UAC_ImageList, ShieldIcon);

  UAC_ButtonImageList.margin.Left := ScaleX(2);
  UAC_ButtonImageList.margin.Top := ScaleY(2);
  UAC_ButtonImageList.margin.Right := ScaleX(0);
  UAC_ButtonImageList.margin.Bottom := ScaleY(4);
  UAC_ButtonImageList.uAlign := 0;

  
  Finished_Notice_Label := TNewStaticText.Create(WizardForm.FinishedPage);
  Finished_Notice_Label.Parent := WizardForm.FinishedPage;
  Finished_Notice_Label.Top := WizardForm.FinishedPage.Height - ScaleY(48);
  Finished_Notice_Label.Left := WizardForm.FinishedLabel.Left;
  Finished_Notice_Label.Caption := '* Restart Steam to see WSE2 in your library *';
  Finished_Notice_Label.Height := ScaleY(Finished_Notice_Label.Height);
  Finished_Notice_Label.Hide();
end;